# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  spec:
    desc: Run Crystal specs
    cmds:
      - crystal spec

  lint:
    desc: Run Ameba linter
    cmds:
      - bin/ameba

  coverage:
    desc: Run code coverage
    cmds:
      - scripts/coverage.sh

  actionlint:
    desc: Lint GitHub Actions workflows
    cmds:
      - actionlint

  unicode:
    desc: Download and generate unicode tables
    cmds:
      - crystal run scripts/gen_unicode.cr

  default:
    desc: Run default spec-lint checks
    deps: [spec, lint]
