# Generates src/foundation/unicode/east_asian_width.cr from the vendored `data/unicode/EastAsianWidth.txt` file.  We only need to run this when bumping the Unicode version.

require "http/client"

UNICODE_VERSION = "17.0.0"
SOURCE          = "data/unicode/EastAsianWidth.txt"
OUTPUT          = "src/foundation/unicode/east_asian_width.cr"
SOURCE_URL      = "https://www.unicode.org/Public/#{UNICODE_VERSION}/ucd/EastAsianWidth.txt"

# East Asian Width values that occupy two terminal cells.
WIDE = {"W", "F"}

# Per the file header, unassigned code points in these blocks default to Wide
DEFAULT_WIDE = [
  {0x3400, 0x4DBF},   # CJK Unified Ideographs Extension A
  {0x4E00, 0x9FFF},   # CJK Unified Ideographs
  {0xF900, 0xFAFF},   # CJK Compatibility Ideographs
  {0x20000, 0x2FFFD}, # Plane 2 (undesignated default Wide)
  {0x30000, 0x3FFFD}, # Plane 3 (undesignated default Wide)
]
# Download the vendored source if it is missing or does not match UNICODE_VERSION.
unless File.exists?(SOURCE) && File.open(SOURCE, &.gets).to_s.includes?(UNICODE_VERSION)
  puts "Downloading #{SOURCE_URL}"
  Dir.mkdir_p(File.dirname(SOURCE))
  response = HTTP::Client.get(SOURCE_URL)
  raise "download failed: HTTP #{response.status_code}" unless response.success?
  File.write(SOURCE, response.body)
end

ranges = [] of Tuple(Int32, Int32)

File.each_line(SOURCE) do |raw|
  line = raw.split('#', 2).first.strip
  next if line.empty?
  cols = line.split(';')
  next unless cols.size == 2
  next unless WIDE.includes?(cols[1].strip)

  field = cols[0].strip
  if field.includes?("..")
    lo, hi = field.split("..")
    ranges << {lo.to_i(16), hi.to_i(16)}
  else
    cp = field.to_i(16)
    ranges << {cp, cp}
  end
end

ranges.concat(DEFAULT_WIDE)
ranges.sort_by! { |rng| rng[0] }

# Merge overlapping or adjacent ranges into the smallest set.
merged = [] of Tuple(Int32, Int32)
ranges.each do |rng|
  if (last = merged.last?) && rng[0] <= last[1] + 1
    merged[-1] = {last[0], Math.max(last[1], rng[1])}
  else
    merged << rng
  end
end

File.open(OUTPUT, "w") do |io|
  io.puts "# This file is generated by scripts/gen_unicode.cr. DO NOT EDIT."
  io.puts "# Source: #{SOURCE} (Unicode #{UNICODE_VERSION})"
  io.puts "# Regenerate with: crystal run scripts/gen_unicode.cr"
  io.puts
  io.puts "module Foundation::Unicode"
  io.puts "  # Sorted, merged code-point ranges whose East Asian Width is Wide or Fullwidth (eg two terminal cells)."
  io.puts "  EAST_ASIAN_WIDE = ["
  merged.each do |rng|
    io.puts "    0x#{rng[0].to_s(16).upcase}_u32..0x#{rng[1].to_s(16).upcase}_u32,"
  end
  io.puts "  ]"
  io.puts
  io.puts "  # Returns true if *codepoint* occupies two terminal cells (Wide or Fullwidth)."
  io.puts "  def self.wide?(codepoint : Int32) : Bool"
  io.puts "    target = codepoint.to_u32"
  io.puts "    lo, hi = 0, EAST_ASIAN_WIDE.size - 1"
  io.puts "    while lo <= hi"
  io.puts "      mid = (lo + hi) // 2"
  io.puts "      range = EAST_ASIAN_WIDE[mid]"
  io.puts "      if target < range.begin"
  io.puts "        hi = mid - 1"
  io.puts "      elsif target > range.end"
  io.puts "        lo = mid + 1"
  io.puts "      else"
  io.puts "        return true"
  io.puts "      end"
  io.puts "    end"
  io.puts "    false"
  io.puts "  end"
  io.puts "end"
end
