name: PR Specs

on:
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "spec/**"
      - "shard.yml"
      - "shard.lock"

env:
  CRYSTAL_VERSION: "1.20.1"

jobs:
  spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: crystal-lang/install-crystal@cdf26dcd488490c9939e9d4d62cab169c9e4f20d # v1.8.2
        with:
          crystal: ${{ env.CRYSTAL_VERSION }}

      - name: Cache shards and ameba binary
        id: cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: |
            lib
            bin/ameba
          # cache invalidates when any shard dependencies change or crystal version changes. Cache on shard.yml because library shards don't get their shard.lock file committed.
          key: ameba-${{ runner.os }}-crystal-${{ env.CRYSTAL_VERSION }}-${{ hashFiles('shard.yml') }}

      - name: Install shards
        # trying to skip ameba postinstall (which takes time to compile and isn't used for specs anyways) just make this step fail.
        # so just use a shard cache instead.
        run: shards install

      - name: Run specs
        run: crystal spec
